spring.application.name=kinoman
# Dane po??czenia
spring.datasource.url=jdbc:mysql://localhost:3306/kinoman_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Admin

# Hibernate - serce JPA (automatycznie tworzy tabele)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# TMDB API Configuration

tmdb.api.key=${TMDB_API_KEY}
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.image-url=https://image.tmdb.org/t/p/w500